### PR TITLE
yetus on master and main branches only

### PR DESCRIPTION
**Pull request by deitch**
Also removed the funny regex, as those semver-ish branches are an eve thing, not an eve-api thing

### CODE REVIEW

**Comment by deitch** [comment]
Ha, yetus is running on it! To you, @eriknordmark

**Comment by deitch** [comment]
Any idea what yetus is complaining about?

**Comment by eriknordmark** [comment]
> Any idea what yetus is complaining about?
Something about token expired. I restarted it.

**Review by eriknordmark — COMMENTED** [review]
But we don't have any master branch here so it's confusing to leave that in

**Review by eriknordmark — APPROVED** [review]
Yamllint issues from the re-run of yetus.  Once they are fixed you can merge. But did protocomp get configured? I didn't see it in the log output

**Comment by deitch** [comment]
> Yamllint issues from the re-run of yetus. Once they are fixed you can merge. 

Where do you see them? Nothing annotated on the files from the PR, nothing in the [output of the run](https://github.com/lf-edge/eve-api/actions/runs/6022043467/job/16360324906?pr=21).

> here so it's confusing to leave that in

True, it was just habit. We can remove it.

**Comment by deitch** [comment]
> But did protocomp get configured? I didn't see it in the log output

No idea. I just took this as-is from eve.

**Pull request merged**
