### PR TITLE
fix broken path

### PR DESCRIPTION
**Pull request by deitch**
#4 accidentally introduced the path as `lf-edge/eve/api/go` instead of `lf-edge/eve-api/go` in the new and modified files. This fixes it.

### CODE REVIEW

**Review by uncleDecart — APPROVED** [review]
LGTM

**Comment by deitch** [comment]
Thanks @uncleDecart ; if only I could merge it in with that approval 😄

**Comment by uncleDecart** [comment]
at least I tried @deitch :D

**Review by eriknordmark — APPROVED** [review]
Ok

**Pull request merged**
