### PR TITLE
use correct remote package name in actions

### PR DESCRIPTION
**Pull request by deitch**
fix broken `go install` in actions

### CODE REVIEW

**Comment by deitch** [comment]
I have the various install dependencies. It does check that nothing has changed, i.e. that all the various generations were done. That means going through the generated files that have changed, to ensure it all is compatible.

**Comment by deitch** [comment]
Ran against a consistent v3.21.9, which was the last run on this prior to switch. It _should_ pass now.

**Comment by deitch** [comment]
And now it appears happy.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
